// Hide auto-generated figure captions from R Markdown chunks
(function() {
  'use strict';
  
  function hideAutoGeneratedCaptions() {
    const pattern = /^plot of chunk unnamed-chunk-\d+$/;
    const captions = document.querySelectorAll('.figcaption');
    
    captions.forEach(function(caption) {
      const text = caption.textContent.trim();
      if (pattern.test(text)) {
        // Use visibility: hidden to maintain spacing
        caption.style.visibility = 'hidden';
      }
    });
  }
  
  // Run on DOM ready
  if (document.readyState === 'loading') {
    document.addEventListener('DOMContentLoaded', hideAutoGeneratedCaptions);
  } else {
    // DOM is already ready
    hideAutoGeneratedCaptions();
  }
})();
